# Generated by Django 2.0.6 on 2018-09-09 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recon', '0002_surl'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sudata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='子域名')),
            ],
        ),
        migrations.AlterField(
            model_name='surl',
            name='url',
            field=models.URLField(verbose_name='查询域名'),
        ),
        migrations.AddField(
            model_name='sudata',
            name='uid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recon.Surl', verbose_name='域名'),
        ),
    ]
