# Generated by Django 2.0.6 on 2018-10-09 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suburl', models.CharField(max_length=100, unique=True, verbose_name='子域名')),
                ('ip', models.GenericIPAddressField(verbose_name='IP地址')),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.Src', verbose_name='主域名')),
            ],
        ),
    ]
