# Generated by Django 2.0.6 on 2018-10-09 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0003_auto_20181009_1608'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='src',
            options={'verbose_name': 'src', 'verbose_name_plural': 'src'},
        ),
        migrations.AlterModelTable(
            name='src',
            table='src',
        ),
    ]
