# Generated by Django 2.0.6 on 2018-10-11 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0004_auto_20181009_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='suburl',
            field=models.CharField(max_length=100, verbose_name='子域名'),
        ),
    ]
